### PR TITLE
add_target

### PR DESCRIPTION
**Pull request by Sir-FIS**
add targets to output﻿

### CODE REVIEW

**Comment by Sir-FIS** [comment]
@xFreed0m

**Review by xFreed0m — CHANGES_REQUESTED** [review]
you are missing a space on line 235 (:

**Comment by xFreed0m** [comment]
fix a small typo (missing space) and i'll merge

**Comment by Sir-FIS** [comment]
done :)

**Review by xFreed0m — APPROVED** [review]

**Pull request merged**
